data = {
    'article1':{
        'pageName': 'Footstep_Tram_Tracks',
        'pageTitle': 'Footsteps - Tram Tracks',
        'pageImage' : '001.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '3 min 24 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed fugiat vitae at molestiae omnis quam. Sed voluptas accusamus ipsam voluptate dolorum soluta iure nulla dignissimos cumque fugiat, labore magni architecto blanditiis temporibus perferendis consectetur reiciendis nemo repellendus a optio beatae ipsum distinctio asperiores porro! Architecto neque officiis cupiditate illo praesentium odit, iusto labore quas et quisquam voluptatibus, quia quaerat obcaecati ut illum?\nDeserunt soluta laudantium tempore adipisci ea eius error ullam ipsum minima facere ex impedit, sapiente fugiat? Numquam pariatur nobis maxime esse delectus ducimus voluptatem minus optio voluptatum facere qui itaque laborum, et ipsam dolore voluptas deserunt eligendi ipsum fugit expedita deleniti asperiores. Ut veritatis enim omnis suscipit. Mollitia necessitatibus iste aperiam expedita voluptatibus error ratione quis esse qui debitis dolorem ducimus repellendus ex eaque obcaecati repellat quaerat laudantium reprehenderit.\nunde cumque corrupti praesentium! Obcaecati maxime ducimus id, est accusamus nemo, repellat atque culpa dignissimos, sequi quibusdam cum quisquam. Excepturi obcaecati nostrum, in voluptates tempore sint! Suscipit ipsa reiciendis, vitae expedita alias blanditiis placeat, libero eos sequi molestiae, velit ipsum amet. Expedita amet aperiam inventore accusantium quaerat a quae itaque harum numquam. Commodi repellat dicta voluptatum ratione in fugit ad impedit laboriosam mollitia cupiditate.'
        },
    'article2':{
        'pageName': 'Footstep_Bush_Tracks',
        'pageTitle': 'Footsteps - Bush Tracks',
        'pageImage' : '002.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '2 min 38 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consectetur similique nostrum maxime accusamus obcaecati doloribus adipisci recusandae dignissimos autem, eius velit distinctio facere vitae dolore voluptatibus laudantium, quisquam saepe ipsa. Omnis sunt corporis eligendi incidunt molestiae odit! Quasi, qui placeat.\nQuasi consequuntur laborum accusamus necessitatibus alias unde est magni laudantium repellendus quibusdam asperiores officia vero eos suscipit adipisci doloribus, optio provident at! Quae eius doloribus nemo sit delectus recusandae est, nobis et tempora nam eum assumenda eaque corrupti dignissimos, porro dolores praesentium quas hic, nihil error consequatur. Veritatis dolorum labore ipsa odio vero, eaque a, iusto adipisci non aliquam porro quaerat ex sapiente harum, tempora sint voluptatum dolores maiores? Delectus deserunt cum ea officiis. Ab rem blanditiis provident eligendi iste.'},
    'article3':{
        'pageName': 'City_Train',
        'pageTitle': 'City Train',
        'pageImage' : '001.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '3 min 24 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'Capturing oceans sounds have always been by favorite type of recordings and whenever I have chance to be close to the coast I do it. While living in Lisbon, Portugal I got the new Zoom F6 field recorder and with my Wildtronics SAAM, I had a powerhouse duo to record with an incredibly powerful and high-quality stereo array set up!\nOne day in Lisbon, a friend of mine picked me up and drove to Nazare to the watch some of the world tallest waves! If you thought Australia or Hawaii has the biggest waves, come to Portugal. I have never seen anything like this before in my life. Make sure you include Nazare to your bucket list if you ever want to visit Portugal.'
        },
    'article4':{
        'pageName': 'Beach_Sand',
        'pageTitle': 'Beach Sand',
        'pageImage' : '002.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '2 min 38 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'I had fun collecting this cause I could.\nThen I decided to have a new line so I did.'},
    'article5':{
        'pageName': 'Maroubra_Beach',
        'pageTitle': 'Maroubra Beach',
        'pageImage' : '001.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '3 min 24 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'Capturing oceans sounds have always been by favorite type of recordings and whenever I have chance to be close to the coast I do it. While living in Lisbon, Portugal I got the new Zoom F6 field recorder and with my Wildtronics SAAM, I had a powerhouse duo to record with an incredibly powerful and high-quality stereo array set up!\nOne day in Lisbon, a friend of mine picked me up and drove to Nazare to the watch some of the world tallest waves! If you thought Australia or Hawaii has the biggest waves, come to Portugal. I have never seen anything like this before in my life. Make sure you include Nazare to your bucket list if you ever want to visit Portugal.'
        },
    'article6':{
        'pageName': 'Coogee_Beach',
        'pageTitle': 'Coogee Beach',
        'pageImage' : '002.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '2 min 38 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'I had fun collecting this cause I could.\nThen I decided to have a new line so I did.'},
    'article7':{
        'pageName': 'Bondi_Beach',
        'pageTitle': 'Bondi Beach',
        'pageImage' : '001.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '3 min 24 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'Capturing oceans sounds have always been by favorite type of recordings and whenever I have chance to be close to the coast I do it. While living in Lisbon, Portugal I got the new Zoom F6 field recorder and with my Wildtronics SAAM, I had a powerhouse duo to record with an incredibly powerful and high-quality stereo array set up!\nOne day in Lisbon, a friend of mine picked me up and drove to Nazare to the watch some of the world tallest waves! If you thought Australia or Hawaii has the biggest waves, come to Portugal. I have never seen anything like this before in my life. Make sure you include Nazare to your bucket list if you ever want to visit Portugal.'
        },
    'article8':{
        'pageName': 'Manly_Beach',
        'pageTitle': 'Manly Beach',
        'pageImage' : '002.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '2 min 38 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'I had fun collecting this cause I could.\nThen I decided to have a new line so I did.'},
    'article9':{
        'pageName': 'Cronulla_Beach',
        'pageTitle': 'Cronulla Beach',
        'pageImage' : '001.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '3 min 24 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'Capturing oceans sounds have always been by favorite type of recordings and whenever I have chance to be close to the coast I do it. While living in Lisbon, Portugal I got the new Zoom F6 field recorder and with my Wildtronics SAAM, I had a powerhouse duo to record with an incredibly powerful and high-quality stereo array set up!\nOne day in Lisbon, a friend of mine picked me up and drove to Nazare to the watch some of the world tallest waves! If you thought Australia or Hawaii has the biggest waves, come to Portugal. I have never seen anything like this before in my life. Make sure you include Nazare to your bucket list if you ever want to visit Portugal.'
        },
    'article10':{
        'pageName': 'Shelly_Beach',
        'pageTitle': 'Shelly Beach',
        'pageImage' : '002.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '2 min 38 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'I had fun collecting this cause I could.\nThen I decided to have a new line so I did.'},
    'article11':{
        'pageName': 'Bus_Trip',
        'pageTitle': 'Bus Trip',
        'pageImage' : '001.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '3 min 24 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed fugiat vitae at molestiae omnis quam. Sed voluptas accusamus ipsam voluptate dolorum soluta iure nulla dignissimos cumque fugiat, labore magni architecto blanditiis temporibus perferendis consectetur reiciendis nemo repellendus a optio beatae ipsum distinctio asperiores porro! Architecto neque officiis cupiditate illo praesentium odit, iusto labore quas et quisquam voluptatibus, quia quaerat obcaecati ut illum?\nDeserunt soluta laudantium tempore adipisci ea eius error ullam ipsum minima facere ex impedit, sapiente fugiat? Numquam pariatur nobis maxime esse delectus ducimus voluptatem minus optio voluptatum facere qui itaque laborum, et ipsam dolore voluptas deserunt eligendi ipsum fugit expedita deleniti asperiores. Ut veritatis enim omnis suscipit. Mollitia necessitatibus iste aperiam expedita voluptatibus error ratione quis esse qui debitis dolorem ducimus repellendus ex eaque obcaecati repellat quaerat laudantium reprehenderit.\nunde cumque corrupti praesentium! Obcaecati maxime ducimus id, est accusamus nemo, repellat atque culpa dignissimos, sequi quibusdam cum quisquam. Excepturi obcaecati nostrum, in voluptates tempore sint! Suscipit ipsa reiciendis, vitae expedita alias blanditiis placeat, libero eos sequi molestiae, velit ipsum amet. Expedita amet aperiam inventore accusantium quaerat a quae itaque harum numquam. Commodi repellat dicta voluptatum ratione in fugit ad impedit laboriosam mollitia cupiditate.'
        },
    'article12':{
        'pageName': 'Crowded_Center',
        'pageTitle': 'Crowded Center',
        'pageImage' : '002.jpg',
        'pageMetaDescription' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium cumque corrupti aperiam eius sed',
        'pageVideo' : 'https://www.youtube.com/embed/5bsqGX3Inpw',
        'location' : 'Royal National Park, Sydney',
        'audioFormat' : '24 bit / 96-192 kHz',
        'duration' : '2 min 38 sec',
        'recorder' : 'Android Phone',
        'microphone' : 'Onboard Microphone',
        'audioEditing' : 'Audacity',
        'videoAvailable' : 'Uploaded to YouTube',
        'delivery' : 'Digital download on Bandcamp',
        'description' : 'I had fun collecting this cause I could.\nThen I decided to have a new line so I did.'},
}